export const potColors = [
    { name: 'Rose Dust', hex: '#EFA2B1' },
    { name: 'Muted Teal', hex: '#82C9D7' },
    { name: 'Warm Apricot', hex: '#F2CDAC' },
    { name: 'Charcoal Plum', hex: '#626070' },
    { name: 'Dusty Mauve', hex: '#934F6F' },
    { name: 'Olive Mist', hex: '#A6A57A' },
    { name: 'Lavender Fog', hex: '#B9AEDC' },
    { name: 'Steel Blue', hex: '#6488A8' },
    { name: 'Burnt Almond', hex: '#C48A69' },
    { name: 'Deep Teal', hex: '#277C78' },
    { name: 'Velvet Rose', hex: '#C48793' },
    { name: 'Golden Fawn', hex: '#D4AF7F' },
    { name: 'Smoky Lavender', hex: '#B8A1C5' },
];
